---
- name: Install and configure VPN
  hosts: all
  gather_facts: no
  roles:
    - { role: Aplyca.VPN, tags: ["vpn"] }
  post_tasks:
    - name: Test if IPSEC is installed
      shell: "ipsec --version"
      register: result
      failed_when: "'Linux Openswan' not in result.stdout"
    - name: Test if IPSEC is properly installed
      become: yes
      shell: "ipsec verify"
      register: result
      failed_when: "'FAILED' in result.stdout"
