---
- debug: var=vpn verbosity=1
  tags: vars

- name: Make sure packages are present
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{ vpn.packages }}"

- name: Get Public IP
  uri:
    url: https://api.ipify.org
    return_content: yes
  register: public_ip
  tags: vpn_config

- name: Configure IPSEC main setup
  become: yes
  template:
    src: ipsec.conf.j2
    dest: "/etc/ipsec.conf"
  notify:
      - restart ipsec
      - restart xl2tpd

- name: Configure IPSEC VPN settings
  become: yes
  template:
    src: ipsec.vpn.conf.j2
    dest: "/etc/ipsec.d/ipsec.vpn.conf"
  notify:
      - restart ipsec
      - restart xl2tpd

- name: Enable include IPSEC secrets config
  become: yes
  lineinfile:
    dest: "/etc/ipsec.secrets"
    line: "include ipsec.d/ipsec.secrets.inc"
    state: present
  notify:
      - restart ipsec
      - restart xl2tpd

- name: Configure IPSEC secret
  become: yes
  template:
    src: ipsec.secrets.inc.j2
    dest: "/etc/ipsec.d/ipsec.secrets.inc"
  notify:
      - restart ipsec
      - restart xl2tpd
  tags: vpn_config

- name: Configure xl2tpd
  become: yes
  copy:
    src: xl2tpd.conf
    dest: "/etc/xl2tpd/xl2tpd.conf"
  notify:
      - restart ipsec
      - restart xl2tpd

- name: Configure PPP options
  become: yes
  copy:
    src: options.xl2tpd
    dest: "/etc/ppp/options.xl2tpd"
  notify:
      - restart ipsec
      - restart xl2tpd

- name: Configure VPN users
  become: yes
  template:
    src: chap-secrets.j2
    dest: "/etc/ppp/chap-secrets"
  notify:
      - restart ipsec
      - restart xl2tpd
  tags: vpn_users

- name: Configure Kernel VPN support
  become: yes
  copy:
    src: vpn-kernel.conf
    dest: /etc/sysctl.d/99-vpn-kernel.conf
  notify:
      - reload sysctl

# This will work in Ansible 2.0
#- name: Set IPTABLES
#  become: yes
#  iptables:
#    table: nat
#    chain: POSTROUTING
#    source: 192.168.42.0/24
#    in_interface: eth0
#    jump: MASQUERADE
#    comment: "Necessary for VPN"

- name:  Disable ICP redirects
  become: yes
  shell: "for vpn in /proc/sys/net/ipv4/conf/*; do echo 0 > $vpn/accept_redirects; echo 0 > $vpn/send_redirects; done"
  changed_when: False


- name: Set IPTABLES Rules
  become: yes
  template:
    src: iptables.rules.j2
    dest: /etc/iptables.rules
  notify:
      - restart ufw

- name: Set Ip Forward
  become: yes
  shell: "echo 1 > /proc/sys/net/ipv4/ip_forward"
  changed_when: False

- name: Configure IPTABLES load
  become: yes
  copy:
    src: iptablesload
    dest: "/etc/network/if-pre-up.d/iptablesload"
    mode: "a+x"
  notify:
      - restart ufw
