---
- name: Make sure packages are present
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items:
      - openswan
      - xl2tpd

- name: Get Public IP
  uri:
    url: https://api.ipify.org
    return_content: yes
  register: public_ip

- name: Configure IPSEC main setup
  become: yes
  template:
    src: ipsec.conf.j2
    dest: "/etc/ipsec.conf"
  notify:
      - restart ipsec
      - restart xl2tpd

- name: Configure IPSEC VPN settings
  become: yes
  template:
    src: ipsec.vpn.conf.j2
    dest: "/etc/ipsec.d/ipsec.vpn.conf"
  notify:
      - restart ipsec
      - restart xl2tpd

- name: Enable include IPSEC secrets config
  become: yes
  lineinfile:
    dest: "/etc/ipsec.secrets"
    line: "include ipsec.d/ipsec.secrets.inc"
    state: present
  notify:
      - restart ipsec
      - restart xl2tpd

- name: Configure IPSEC secret
  become: yes
  template:
    src: ipsec.secrets.inc.j2
    dest: "/etc/ipsec.d/ipsec.secrets.inc"
  notify:
      - restart ipsec
      - restart xl2tpd

- name: Configure xl2tpd
  become: yes
  copy:
    src: xl2tpd.conf
    dest: "/etc/xl2tpd/xl2tpd.conf"
  notify:
      - restart ipsec
      - restart xl2tpd

- name: Configure PPP options
  become: yes
  copy:
    src: options.xl2tpd
    dest: "/etc/ppp/options.xl2tpd"
  notify:
      - restart ipsec
      - restart xl2tpd

- name: Configure VPN users
  become: yes
  template:
    src: chap-secrets.j2
    dest: "/etc/ppp/chap-secrets"
  notify:
      - restart ipsec
      - restart xl2tpd

# This will work in Ansible 2.0
#- name: Set IPTABLES
#  become: yes
#  iptables:
#    table: nat
#    chain: POSTROUTING
#    source: 192.168.42.0/24
#    in_interface: eth0
#    jump: MASQUERADE
#    comment: "Necessary for VPN"

- name: Set IPTABLES Rules
  become: yes
  shell: "iptables -t nat -A POSTROUTING -s 192.168.42.0/24 -o eth0 -j MASQUERADE"

- name: Set Ip Forward
  become: yes
  shell: "echo 1 > /proc/sys/net/ipv4/ip_forward"

- name: Save IPTABLES rules
  become: yes
  shell: "iptables-save > /etc/iptables.rules"

- name: Configure IPTABLES load
  become: yes
  copy:
    src: iptablesload
    dest: "/etc/network/if-pre-up.d/iptablesload"
    mode: "a+x"
