---

- name: restart ipsec
  become: yes
  service:
    name: ipsec
    state: restarted
    enabled: yes

- name: restart xl2tpd
  become: yes
  service:
    name: xl2tpd
    state: restarted
    enabled: yes

- name: restart ufw
  become: yes
  service:
    name: ufw
    state: restarted
    enabled: yes

- name: reload sysctl
  become: yes
  command: "sysctl -p"
